### ISSUE TITLE
WhenToWork Update

### ISSUE THREAD

**Issue by daltont25** [samyun/Ohio-Union-EMS-Autofill-Tool#17]
WhenToWork has updated their website, causing the script to not be able to grab names.

**Comment by samyun** [comment]
Post a copy of the error message and logs. I'll see if it's a simple fix.

**Comment by daltont25** [comment]
Debug File says:

12/04/2018 04:23:04 PM INFO:******************* Running Autofill Tool *******************
12/04/2018 04:23:04 PM INFO:Reading settings file
12/04/2018 04:23:11 PM INFO:Navigating to WhenToWork
12/04/2018 04:23:17 PM INFO:AV Shift Lead:

Terminal says:

Reading settings file
Enter date (eg December 05 2018 = "12/05/2018").
Press enter to use December 05 2018:
Using 12/5/2018
Navigating to WhenToWork
AV Shift Lead:
Traceback (most recent call last):
  File "autofill_tool.py", line 1419, in <module>
    parsed_list = w2w.get_list_of_schedule(col_num)
  File "autofill_tool.py", line 1096, in get_list_of_schedule
    list_of_cells = list_of_rows[1].find_elements_by_tag_name("td")
IndexError: list index out of range

**Comment by lamarrh** [comment]
Yo Sam, you can run selenium in lambda now 🤯

On Dec 4, 2018, at 4:24 PM, daltont25 <notifications@github.com<mailto:notifications@github.com>> wrote:


Debug File says:

12/04/2018 04:23:04 PM INFO:******************* Running Autofill Tool *******************
12/04/2018 04:23:04 PM INFO:Reading settings file
12/04/2018 04:23:11 PM INFO:Navigating to WhenToWork
12/04/2018 04:23:17 PM INFO:AV Shift Lead:

Terminal says:

Reading settings file
Enter date (eg December 05 2018 = "12/05/2018").
Press enter to use December 05 2018:
Using 12/5/2018
Navigating to WhenToWork
AV Shift Lead:
Traceback (most recent call last):
File "autofill_tool.py", line 1419, in
parsed_list = w2w.get_list_of_schedule(col_num)
File "autofill_tool.py", line 1096, in get_list_of_schedule
list_of_cells = list_of_rows[1].find_elements_by_tag_name("td")
IndexError: list index out of range

**Comment by samyun** [comment]
You mean in a lambda function? Or what?

**Comment by lamarrh** [comment]
Yup

Sent from my iPhone

On Dec 23, 2018, at 8:03 PM, Samuel Yun <notifications@github.com<mailto:notifications@github.com>> wrote:


You mean in a lambda function? Or what?

**Comment by samyun** [comment]
Neat

**Comment by samyun** [comment]
By the way it's fixed now @daltont25

**Comment by daltont25** [comment]
[debug_log.log](https://github.com/samyun/Ohio-Union-EMS-Autofill-Tool/files/2734500/debug_log.log)

**Comment by samyun** [comment]
@daltont25 fixed it for realsies 

Looks like I have access to EMS (again?) so I verified by scheduling Friday for you.

[AV Assignments 2019-1-11.txt](https://github.com/samyun/Ohio-Union-EMS-Autofill-Tool/files/2744135/AV.Assignments.2019-1-11.txt)

**Comment by daltont25** [comment]
Reading settings file
Enter date (eg January 17 2019 = "01/17/2019").
Press enter to use January 17 2019:
Using 1/17/2019
Navigating to WhenToWork
AV Shift Lead:
 - 'Taylor Basinger' @ '07:00 AM' - '12:00 PM'
 - 'Alex Hempel' @ '12:00 PM' - '04:00 PM'
 - 'Alex Hempel' @ '04:00 PM' - '09:00 PM'
AV Student Manager:
 - 'Tristen Dalton' @ '06:30 PM' - '12:00 AM'
AV Technician:
Traceback (most recent call last):
  File "autofill_tool.py", line 1420, in <module>
    parsed_list = w2w.get_list_of_schedule(col_num)
  File "autofill_tool.py", line 1114, in get_list_of_schedule
    start_datetime = self.parse_w2w_time(time_list[0])
  File "autofill_tool.py", line 1071, in parse_w2w_time
    dt = datetime.datetime.strptime(time_to_parse, '%I%p')
  File "C:\Python3\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Python3\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%I%p'

01/16/2019 11:23:20 AM INFO:******************* Running Autofill Tool *******************
01/16/2019 11:23:20 AM INFO:Reading settings file
01/16/2019 11:23:22 AM INFO:Navigating to WhenToWork
01/16/2019 11:23:36 AM INFO:AV Shift Lead:
01/16/2019 11:23:37 AM DEBUG:Parsed '7am' to '07:00 AM'
01/16/2019 11:23:37 AM DEBUG:Parsed '12pm' to '12:00 PM'
01/16/2019 11:23:37 AM INFO: - 'Taylor Basinger' @ '07:00 AM' - '12:00 PM'
01/16/2019 11:23:37 AM DEBUG:Parsed '12pm' to '12:00 PM'
01/16/2019 11:23:37 AM DEBUG:Parsed '4pm' to '04:00 PM'
01/16/2019 11:23:37 AM INFO: - 'Alex Hempel' @ '12:00 PM' - '04:00 PM'
01/16/2019 11:23:37 AM DEBUG:Parsed '4pm' to '04:00 PM'
01/16/2019 11:23:37 AM DEBUG:Parsed '9pm' to '09:00 PM'
01/16/2019 11:23:37 AM INFO: - 'Alex Hempel' @ '04:00 PM' - '09:00 PM'
01/16/2019 11:23:37 AM INFO:AV Student Manager:
01/16/2019 11:23:38 AM DEBUG:Parsed '6:30pm' to '06:30 PM'
01/16/2019 11:23:38 AM DEBUG:Parsed '12am' to '12:00 AM'
01/16/2019 11:23:38 AM INFO: - 'Tristen Dalton' @ '06:30 PM' - '12:00 AM'
01/16/2019 11:23:38 AM INFO:AV Technician:
01/16/2019 11:23:38 AM DEBUG:Parsed '7am' to '07:00 AM'
01/16/2019 11:23:38 AM DEBUG:Parsed '1pm' to '01:00 PM'




SAM WHY THIS BREAK A LOT NOW

**Comment by lamarrh** [comment]
It’s because 

ValueError: time data '' does not match format '%I%p' lol

**Comment by samyun** [comment]
Fixed - for some reason, W2W has an empty line.
